/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tienda;

import Dbconect.basedatos;
import Dbconect.metodos;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author andree
 */
public class pedidos extends javax.swing.JFrame {

    /**
     * Creates new form pedidos
     */
    
    Cola mesa = new Cola();
    Cola delivery = new Cola();
    DefaultListModel modelo_delivery = new DefaultListModel();
    DefaultListModel modelo_mesa = new DefaultListModel();
    Connection cn;
    Statement s;
    ResultSet rs;
    float precio_total = 0;
    float precioproducto1 = 0;
    float precioproducto2 = 0;
    float precioproducto3 = 0;
    float precioproducto4 = 0;
    float precioproducto5 = 0;
    
    
   
    
    public pedidos() {
        initComponents();
        Cargar_Productos();
        Cargar_Registros();
    }
    
    
    private void Cargar_Productos(){
        Connection conectar;
        Statement s;
        ResultSet result=null;
        
        String SSQL = "SELECT product_name FROM ajvznjo29l0fdb0a.products ORDER BY product_id ASC";
        
        try{
            conectar = basedatos.conectar();
            s = conectar.createStatement();
            result = s.executeQuery(SSQL);
            
            producto1.addItem("Seleccione una opción");
            producto2.addItem("Seleccione una opción");
            producto3.addItem("Seleccione una opción");
            producto4.addItem("Seleccione una opción");
            producto5.addItem("Seleccione una opción");
            
            
            while (result.next()) {

                producto1.addItem(result.getString("product_name"));
                producto2.addItem(result.getString("product_name"));
                producto3.addItem(result.getString("product_name"));
                producto4.addItem(result.getString("product_name"));
                producto5.addItem(result.getString("product_name"));
                

            }
         
            
        }catch(SQLException e){
            System.out.println(e);
        }
        
        
    }
    
    
    private void Cargar_Registros(){
        
        Connection cn;
        Statement s;
        ResultSet rs;
        try{
            DefaultTableModel modelo_registro = new DefaultTableModel();
            this.registros.setModel(modelo_registro);
            cn = basedatos.conectar();//cn variable de tipo coneccion
            s = cn.createStatement();
            rs = s.executeQuery("select * from registro ORDER BY idRegistro ASC ");
            ResultSetMetaData rsMd = rs.getMetaData();
            
            int cantidadColumnas = rsMd.getColumnCount();
            
            for (int i = 1; i <= cantidadColumnas; i++) {
                modelo_registro.addColumn(rsMd.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo_registro.addRow(fila);
            }
            rs.close();
            cn.close();
            
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        producto1 = new javax.swing.JComboBox<>();
        qty1 = new javax.swing.JTextField();
        producto2 = new javax.swing.JComboBox<>();
        qty2 = new javax.swing.JTextField();
        qty3 = new javax.swing.JTextField();
        producto3 = new javax.swing.JComboBox<>();
        qty4 = new javax.swing.JTextField();
        qty5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tipo_entrega = new javax.swing.JComboBox<>();
        precio1 = new javax.swing.JLabel();
        precio2 = new javax.swing.JLabel();
        precio4 = new javax.swing.JLabel();
        precio3 = new javax.swing.JLabel();
        precio5 = new javax.swing.JLabel();
        nrodni = new javax.swing.JTextField();
        telef = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        preciototal = new javax.swing.JLabel();
        Ingresar = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        nromesa = new javax.swing.JTextField();
        producto4 = new javax.swing.JComboBox<>();
        producto5 = new javax.swing.JComboBox<>();
        CalcTotal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cliente_name = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_delivery = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        telef_deliv = new javax.swing.JTextField();
        direccion_deliv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        entregardeliv = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        precio_deliv = new javax.swing.JTextField();
        verdatosdeliv = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lista_mesa = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nombre_mesa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mesa_mesa = new javax.swing.JTextField();
        entregarmesa = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        precio_mesa = new javax.swing.JTextField();
        verdatosmesa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        registros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DNI:");

        jLabel4.setText("Nro. Telef:");

        jLabel6.setText("Productos:");

        producto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto1ActionPerformed(evt);
            }
        });

        qty1.setText("0");
        qty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty1ActionPerformed(evt);
            }
        });

        producto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto2ActionPerformed(evt);
            }
        });

        qty2.setText("0");
        qty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty2ActionPerformed(evt);
            }
        });

        qty3.setText("0");
        qty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty3ActionPerformed(evt);
            }
        });

        producto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto3ActionPerformed(evt);
            }
        });

        qty4.setText("0");
        qty4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty4ActionPerformed(evt);
            }
        });

        qty5.setText("0");
        qty5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo:");

        tipo_entrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa", "Delivery" }));
        tipo_entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_entregaActionPerformed(evt);
            }
        });

        precio1.setText("s/. --");

        precio2.setText("s/. --");

        precio4.setText("s/. --");

        precio3.setText("s/. --");

        precio5.setText("s/. --");

        nrodni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrodniActionPerformed(evt);
            }
        });

        telef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefActionPerformed(evt);
            }
        });

        jLabel9.setText("Direccion:");

        direccion.setEditable(false);
        direccion.setEnabled(false);

        jLabel10.setText("Total:");

        preciototal.setText("s/. --");

        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });

        jLabel12.setText("Mesa:");

        nromesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nromesaActionPerformed(evt);
            }
        });

        producto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto4ActionPerformed(evt);
            }
        });

        producto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto5ActionPerformed(evt);
            }
        });

        CalcTotal.setText("Calcular");
        CalcTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcTotalActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipo_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nrodni, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nromesa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cliente_name, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telef, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CalcTotal)
                                        .addGap(30, 30, 30))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(producto1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(producto2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(producto3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(producto4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(producto5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(qty1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(qty2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(qty3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(qty4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(qty5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(precio3)
                                        .addComponent(precio4))
                                    .addComponent(precio2)
                                    .addComponent(precio1)
                                    .addComponent(precio5)
                                    .addComponent(preciototal))
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrodni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cliente_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(telef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tipo_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nromesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precio1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precio2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precio3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qty4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precio4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qty5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precio5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(producto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(producto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(producto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(producto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(producto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preciototal)
                                .addGap(18, 18, 18)
                                .addComponent(Ingresar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CalcTotal)
                                    .addComponent(jLabel10))
                                .addGap(38, 38, 38))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Ingresar Pedidos", jPanel1);

        jLabel3.setText("Pendientes:");

        jScrollPane2.setViewportView(Lista_delivery);

        jLabel5.setText("Nro. Telef:");

        telef_deliv.setEditable(false);
        telef_deliv.setEnabled(false);
        telef_deliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telef_delivActionPerformed(evt);
            }
        });

        direccion_deliv.setEditable(false);
        direccion_deliv.setEnabled(false);

        jLabel11.setText("Direccion:");

        entregardeliv.setText("Entregar Pedido");
        entregardeliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregardelivActionPerformed(evt);
            }
        });

        jLabel16.setText("Precio:");

        precio_deliv.setEditable(false);
        precio_deliv.setEnabled(false);

        verdatosdeliv.setText("Ver Datos");
        verdatosdeliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdatosdelivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(precio_deliv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(telef_deliv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(direccion_deliv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(verdatosdeliv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entregardeliv, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(telef_deliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(direccion_deliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(precio_deliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entregardeliv)
                            .addComponent(verdatosdeliv))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delivery", jPanel3);

        jScrollPane3.setViewportView(Lista_mesa);

        jLabel7.setText("Pendientes:");

        jLabel13.setText("Nombre:");

        nombre_mesa.setEditable(false);
        nombre_mesa.setEnabled(false);
        nombre_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_mesaActionPerformed(evt);
            }
        });

        jLabel14.setText("Mesa:");

        mesa_mesa.setEditable(false);
        mesa_mesa.setEnabled(false);

        entregarmesa.setText("Entregar Pedido");
        entregarmesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregarmesaActionPerformed(evt);
            }
        });

        jLabel15.setText("Precio:");

        precio_mesa.setEditable(false);
        precio_mesa.setEnabled(false);

        verdatosmesa.setText("Ver Datos");
        verdatosmesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdatosmesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(verdatosmesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entregarmesa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mesa_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombre_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precio_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(nombre_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(mesa_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entregarmesa)
                            .addComponent(verdatosmesa))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mesa", jPanel2);

        registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(registros);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefActionPerformed

    private void nrodniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrodniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrodniActionPerformed

    private void tipo_entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_entregaActionPerformed
        // TODO add your handling code here:
        if(tipo_entrega.getSelectedItem()=="Delivery"){
            direccion.setEnabled(true);
            direccion.setEditable(true);
            nromesa.setEnabled(false);
            nromesa.setEditable(false);
        }
        else{
            direccion.setEnabled(false);
            direccion.setEditable(false);
            nromesa.setEnabled(true);
            nromesa.setEditable(true);
        }
    }//GEN-LAST:event_tipo_entregaActionPerformed

    private void qty5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty5ActionPerformed

    private void qty4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty4ActionPerformed

    private void producto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto3ActionPerformed
        // TODO add your handling code here:
        if(producto3.getSelectedItem()!="Seleccione una opción"){
            precioproducto3 = metodos.buscarPrecioProducto(producto3.getSelectedItem().toString());
            precio3.setText("s/."+precioproducto3);
        }else{
            precio3.setText("s/.");
        }
    }//GEN-LAST:event_producto3ActionPerformed

    private void qty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty3ActionPerformed

    private void qty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty2ActionPerformed

    private void producto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto2ActionPerformed
        // TODO add your handling code here:
        if(producto2.getSelectedItem()!="Seleccione una opción"){
            precioproducto2 = metodos.buscarPrecioProducto(producto2.getSelectedItem().toString());
            precio2.setText("s/."+precioproducto2);
        }else{
            precio2.setText("s/.");
        }
    }//GEN-LAST:event_producto2ActionPerformed

    private void qty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_qty1ActionPerformed

    private void producto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto1ActionPerformed
        // TODO add your handling code here:
        if(producto1.getSelectedItem()!="Seleccione una opción"){
            precioproducto1 = metodos.buscarPrecioProducto(producto1.getSelectedItem().toString());
            precio1.setText("s/."+precioproducto1);
        }else{
            precio1.setText("s/.");
        }
    }//GEN-LAST:event_producto1ActionPerformed

    private void telef_delivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telef_delivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telef_delivActionPerformed

    private void nromesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nromesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nromesaActionPerformed

    private void nombre_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_mesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_mesaActionPerformed

    private void producto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto4ActionPerformed
        // TODO add your handling code here:
        if(producto4.getSelectedItem()!="Seleccione una opción"){
            precioproducto4 = metodos.buscarPrecioProducto(producto4.getSelectedItem().toString());
            precio4.setText("s/."+precioproducto4);
        }else{
            precio4.setText("s/.");
        }
    }//GEN-LAST:event_producto4ActionPerformed

    private void producto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto5ActionPerformed
        // TODO add your handling code here:
        if(producto5.getSelectedItem()!="Seleccione una opción"){
            precioproducto5 = metodos.buscarPrecioProducto(producto5.getSelectedItem().toString());
            precio5.setText("s/."+precioproducto5);
        }else{
            precio5.setText("s/.");
        }
    }//GEN-LAST:event_producto5ActionPerformed

    private void CalcTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcTotalActionPerformed
        // TODO add your handling code here:
        precio_total=0;
        if(qty1.getText()!=""){
            precio_total=precio_total+precioproducto1*Float.valueOf(qty1.getText());
            preciototal.setText("s/."+precio_total);
        }
        if(qty2.getText()!=""){
            precio_total=precio_total+precioproducto2*Float.valueOf(qty2.getText());
            preciototal.setText("s/."+precio_total);
        }
        if(qty3.getText()!=""){
            precio_total=precio_total+precioproducto3*Float.valueOf(qty3.getText());
            preciototal.setText("s/."+precio_total);
        }
        if(qty4.getText()!=""){
            precio_total=precio_total+precioproducto4*Float.valueOf(qty4.getText());
            preciototal.setText("s/."+precio_total);
        }
        if(qty5.getText()!=""){
            precio_total=precio_total+precioproducto5*Float.valueOf(qty5.getText());
            preciototal.setText("s/."+precio_total);
        }
        
        preciototal.setText("s/."+precio_total);
        
 
    
    }//GEN-LAST:event_CalcTotalActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
        int dni = Integer.parseInt(nrodni.getText());
        int nrotelef = Integer.parseInt(telef.getText());
        String cliente = cliente_name.getText();
        String mesa_nro,direc;
        if(tipo_entrega.getSelectedItem()=="Mesa"){
            mesa_nro = nromesa.getText();
            direc = "";
        }else{
            mesa_nro = "";
            direc = direccion.getText();
            
        }
        
        if(tipo_entrega.getSelectedItem()=="Mesa"){
            mesa.insertar(dni, nrotelef,cliente, mesa_nro, direc, precio_total);
            modelo_mesa.addElement(dni);
            Lista_mesa.setModel(modelo_mesa);
        }else{
            delivery.insertar(dni, nrotelef,cliente, mesa_nro, direc, precio_total);
            modelo_delivery.addElement(dni);
            Lista_delivery.setModel(modelo_delivery);
            
        }
        
        JOptionPane.showMessageDialog(null, "Se ingreso a la cola "+tipo_entrega.getSelectedItem());
        
        nrodni.setText(null);
        telef.setText(null);
        cliente_name.setText(null);
        nromesa.setText(null);
        direccion.setText(null);
        qty1.setText("0");
        qty2.setText("0");
        qty3.setText("0");
        qty4.setText("0");
        qty5.setText("0");
        producto1.setSelectedIndex(0);
        producto2.setSelectedIndex(0);
        producto3.setSelectedIndex(0);
        producto4.setSelectedIndex(0);
        producto5.setSelectedIndex(0);
        
        
        
    }//GEN-LAST:event_IngresarActionPerformed

    private void verdatosdelivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdatosdelivActionPerformed
        // TODO add your handling code here:
        int codi = Lista_delivery.getSelectedIndex();
        telef_deliv.setText(Integer.toString(delivery.gettelef(delivery, codi)));
        direccion_deliv.setText(delivery.getdirec(delivery, codi));
        precio_deliv.setText(Float.toString(delivery.getprecio(delivery, codi)));
        
        
    }//GEN-LAST:event_verdatosdelivActionPerformed

    private void verdatosmesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdatosmesaActionPerformed
        // TODO add your handling code here:
        int codi = Lista_mesa.getSelectedIndex();
        nombre_mesa.setText(mesa.getnombre(mesa, codi));
        mesa_mesa.setText(mesa.getmesa(mesa, codi));
        precio_mesa.setText(Float.toString(mesa.getprecio(mesa, codi)));
    }//GEN-LAST:event_verdatosmesaActionPerformed

    private void entregardelivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregardelivActionPerformed
        // TODO add your handling code here:
        
        modelo_delivery.remove(0);
        Lista_delivery.setModel(modelo_delivery);
        int strdni = delivery.getdni(delivery, 0);
        int strtel = delivery.gettelef(delivery,0);
        String strnombre = delivery.getnombre(delivery, 0);
        String strmesa = delivery.getmesa(delivery, 0);
        String strdire = delivery.getdirec(delivery, 0);
        float strprecio = delivery.getprecio(delivery, 0);
        metodos.ingresarRegistro(strdni, strtel, strnombre, strmesa, strdire, strprecio);
        
        delivery.extraer();
        Cargar_Registros();
        
        
    }//GEN-LAST:event_entregardelivActionPerformed

    private void entregarmesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregarmesaActionPerformed
        // TODO add your handling code here:
        
        modelo_mesa.remove(0);
        Lista_mesa.setModel(modelo_mesa);
        int strdni = mesa.getdni(mesa, 0);
        int strtel = mesa.gettelef(mesa,0);
        String strnombre = mesa.getnombre(mesa, 0);
        String strmesa = mesa.getmesa(mesa, 0);
        String strdire = mesa.getdirec(mesa, 0);
        float strprecio = mesa.getprecio(mesa, 0);
        metodos.ingresarRegistro(strdni, strtel, strnombre, strmesa, strdire, strprecio);
        
        mesa.extraer();
        Cargar_Registros();
        
        
    }//GEN-LAST:event_entregarmesaActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pedidos().setVisible(true);
                
                
    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcTotal;
    private javax.swing.JToggleButton Ingresar;
    private javax.swing.JList<String> Lista_delivery;
    private javax.swing.JList<String> Lista_mesa;
    private javax.swing.JTextField cliente_name;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField direccion_deliv;
    private javax.swing.JButton entregardeliv;
    private javax.swing.JButton entregarmesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mesa_mesa;
    private javax.swing.JTextField nombre_mesa;
    private javax.swing.JTextField nrodni;
    private javax.swing.JTextField nromesa;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel precio3;
    private javax.swing.JLabel precio4;
    private javax.swing.JLabel precio5;
    private javax.swing.JTextField precio_deliv;
    private javax.swing.JTextField precio_mesa;
    private javax.swing.JLabel preciototal;
    private javax.swing.JComboBox<String> producto1;
    private javax.swing.JComboBox<String> producto2;
    private javax.swing.JComboBox<String> producto3;
    private javax.swing.JComboBox<String> producto4;
    private javax.swing.JComboBox<String> producto5;
    private javax.swing.JTextField qty1;
    private javax.swing.JTextField qty2;
    private javax.swing.JTextField qty3;
    private javax.swing.JTextField qty4;
    private javax.swing.JTextField qty5;
    private javax.swing.JTable registros;
    private javax.swing.JTextField telef;
    private javax.swing.JTextField telef_deliv;
    private javax.swing.JComboBox<String> tipo_entrega;
    private javax.swing.JButton verdatosdeliv;
    private javax.swing.JButton verdatosmesa;
    // End of variables declaration//GEN-END:variables
}
